### ISSUE TITLE
Architecture

### ISSUE THREAD

**Issue by babacarcissedia** [afritech-connect/blog#1]
## Roadmap
- [ ] Nov 22nd, infrastructure (tech, servers, domain, DDOS protection)
- [ ] Nov 29th, Go live with hello world. First deployment of empty shell
- [ ] Dec 6th, Go live with bare bone user account
- [ ] Dec 13rd, Go live with bare bone articles without medias, comments

## Finances
- [ ] domain
- [ ] servers
- [ ] time
- [ ] code
- [ ] file storage

## Features / stories
- [ ] user can create account
- [ ] article CRUD
- [ ] user can request edit on article. Author can see edit requests

Who writes the articles ?
- any member

Who is member ?
- name
- email

Who vets the content ?
- needs to be member of the community
- [ ] post an article
- [ ] article can be vetted (`validated_at`, `validated_by`)

## Entities
```
User
|__... as usual
|__bio
- [ ] member can be banned / unbanned ?

Role
|__name
|__key
- List
  * admin -> create_role, create_permission -> CRUD supposed
  * curator -> vet_post
  
Permission
|__name
|__key

Post
|__title
|__subtitle ?
|__link ? embedded video ?
|__slug
|__content
|__created_at
|__updated_at
|__attachments can be images or videos
|__authors
- Who is author ?
  * has posted article ?
- Who is contributor
  * has updated article ?
  * needs


Post edits
|__content as suggestion ?
|__author

Category or Tag
|__

Comment
|__

Likes
|__

Views
|__

```

**Comment by babacarcissedia** [comment]
## Questions

Features ?
Goals ?
* Création d'une communauté
* Partage de connaissances
* Apprentissage continu à travers les article
- blog space ?
- written content of twitter space ?
- online Senegal / African presence
When ?

Website
- blog
  * written ?
  * videos ?
  * projects ?
- teams / members ?
  * charte
  * how to join ?
  * who are we ?
- contact
  * les adhérents (potentiels clients)
  * insérer videos et medias
  * opportunités de networking, de collaboration avec de potentiels partenaires
  * Fournir des tutoriels aux étudiants pourquoi pas
  * interactions avec les lecteurs leurs permettre de poser des questions , échanger des idées
- careers / job board
